%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "is_private": false,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": "This channel is for team-wide communication and announcements. All team members are in this channel."
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C58GTD2MP",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "U591XC8LT",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1493960964,
    "name_normalized": "general",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": true,
    "num_members": 846,
    "name": "general",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": "Company-wide announcements and work-based matters"
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C017PH4G8CX",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UFU0HJU67",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1596300298,
    "name_normalized": "revance-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 13,
    "name": "revance-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": true,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C017XHG8G3G",
    "pending_connected_team_ids": [],
    "creator": "UFXNJ42DT",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1596300291,
    "name_normalized": "latimes-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 17,
    "name": "latimes-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": true,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C0184FM0A2X",
    "pending_connected_team_ids": [],
    "creator": "UNKMJ0U90",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1596300294,
    "name_normalized": "televerde-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 11,
    "name": "televerde-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": true,
    "purpose": {
      "last_set": 1596300295,
      "creator": "UHR2CNW64",
      "value": "Pager Duty and Apisero Shared"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C0184FM0F2P",
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1596300295,
    "name_normalized": "pagerduty-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 9,
    "name": "pagerduty-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C0184FM189Z",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UFU0HJU67",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1596300298,
    "name_normalized": "netsmart-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 17,
    "name": "netsmart-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": true,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C019HSR6QPR",
    "pending_connected_team_ids": [],
    "creator": "UFVJYSLUV",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1599054468,
    "name_normalized": "nursys-staffbot-apisero",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 10,
    "name": "nursys-staffbot-apisero",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 1598943918,
      "creator": "UHR2CNW64",
      "value": "CMCU and Apisero shared channel."
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C01AJU3EDU0",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1598943917,
    "name_normalized": "cmcu-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 7,
    "name": "cmcu-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C01B5HKPB36",
    "previous_names": [
      "fab-project-team"
    ],
    "pending_connected_team_ids": [],
    "creator": "UPQNZS4F6",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1600446254,
    "name_normalized": "fab-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 1608200941,
    "is_archived": false,
    "is_general": false,
    "num_members": 6,
    "name": "fab-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 1603460252,
      "creator": "U017CP9509Z",
      "value": "chaneel to connect cabi team,apisero team and hotwaxsystem team"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C01D76U042E",
    "previous_names": [
      "external-mt6-cabi-apisero"
    ],
    "pending_connected_team_ids": [],
    "creator": "U017CP9509Z",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1603460251,
    "name_normalized": "cabi-apisero-shared",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 1612785831,
    "is_archived": false,
    "is_general": false,
    "num_members": 5,
    "name": "cabi-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01E5PYCQSK",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "U018BSJ07NY",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1605189508,
    "name_normalized": "shopify-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 16,
    "name": "shopify-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 1605286271,
      "creator": "U01E7FCP5TK",
      "value": "Rogers Communication"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C01E9F9Q0KZ",
    "previous_names": [
      "rogers-apisero-internal",
      "fieldrogers-apisero-shared",
      "field_rogers"
    ],
    "pending_connected_team_ids": [],
    "creator": "U01E7FCP5TK",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1605286270,
    "name_normalized": "field-rogers-internal",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 17,
    "name": "field-rogers-internal",
    "topic": {
      "last_set": 1605286467,
      "creator": "U01DMD249UN",
      "value": "Field channel for Rogers: To collaborate/sync on Rogers activities"
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1605621928,
      "creator": "UHR2CNW64",
      "value": "Apisero and Sears Holding/Transformco shared channel."
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01EXG9JV51",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1605621927,
    "name_normalized": "searshtransform-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 8,
    "name": "searshtransform-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01FML61PH7",
    "previous_names": [
      "apisero-patelco"
    ],
    "pending_connected_team_ids": [],
    "creator": "U017UAV5GF4",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1605926840,
    "name_normalized": "patelco-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 8,
    "name": "patelco-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1607106457,
      "creator": "UHR2CNW64",
      "value": "Apisero FormeLife Shared Slack channel"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01FSC0RU2K",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1607106456,
    "name_normalized": "formelife-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 11,
    "name": "formelife-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": false,
    "id": "C01GMMRK6JH",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "URA066S1F",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1607707256,
    "name_normalized": "uccu-apisero-shared-channel",
    "is_ext_shared": false,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 14,
    "name": "uccu-apisero-shared-channel",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1607340201,
      "creator": "UHR2CNW64",
      "value": "Saint Gobain Apisero Shared Channel."
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01GP7K0A0H",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1607340201,
    "name_normalized": "saintgobain-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 31,
    "name": "saintgobain-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1608053022,
      "creator": "UHR2CNW64",
      "value": "Goodyear and Apisero Slack Channel"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01GYU3H24A",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1608053021,
    "name_normalized": "goodyear-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 11,
    "name": "goodyear-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01H0JVD4CA",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UQ66C9SNB",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1608101103,
    "name_normalized": "goosehead-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 21,
    "name": "goosehead-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01HB5654MA",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1608214360,
    "name_normalized": "supplychainsolutions-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 11,
    "name": "supplychainsolutions-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1608656570,
      "creator": "UHR2CNW64",
      "value": "aviatrix and apisero shared channel."
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01HCPJNQN9",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1608656569,
    "name_normalized": "aviatrix-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 9,
    "name": "aviatrix-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1609858958,
      "creator": "UHR2CNW64",
      "value": "LiquiBox and Apisero Shared Slack channel"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01HU7SUG0N",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1609858958,
    "name_normalized": "liquibox-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 12,
    "name": "liquibox-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": true,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1610094107,
      "creator": "U017CP9509Z",
      "value": "aviatrix and apisero shared channel"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01HUBE8GPR",
    "pending_connected_team_ids": [],
    "creator": "U017CP9509Z",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1610094106,
    "name_normalized": "azfcu-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 9,
    "name": "azfcu-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1608656191,
      "creator": "UHR2CNW64",
      "value": "a4media and apisero slack shared channel."
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01J5LVNAHE",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1608656190,
    "name_normalized": "a4media-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 12,
    "name": "a4media-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "is_private": false,
    "conversation_host_id": "T596V2PB7",
    "purpose": {
      "last_set": 1608657558,
      "creator": "UHR2CNW64",
      "value": "ordermark and apisero shared channel"
    },
    "is_pending_ext_shared": false,
    "pending_shared": [],
    "is_channel": true,
    "is_shared": true,
    "id": "C01J5NRHG56",
    "previous_names": [],
    "pending_connected_team_ids": [],
    "creator": "UHR2CNW64",
    "is_im": false,
    "is_member": true,
    "is_mpim": false,
    "created": 1608657557,
    "name_normalized": "ordermark-apisero-shared",
    "is_ext_shared": true,
    "is_group": false,
    "unlinked": 0,
    "is_archived": false,
    "is_general": false,
    "num_members": 13,
    "name": "ordermark-apisero-shared",
    "topic": {
      "last_set": 0,
      "creator": "",
      "value": ""
    },
    "is_org_shared": false,
    "parent_conversation": null
  },
  {
    "id": "C01J90SP6HG",
    "name": "flaskparking-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1610088759,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "flaskparking-apisero-shared",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UHR2CNW64",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "Flash Parking and Apisero Shared Slack Channel.",
      "creator": "UHR2CNW64",
      "last_set": 1610088759
    },
    "previous_names": [],
    "num_members": 16
  },
  {
    "id": "C01JET476UV",
    "name": "g2rl-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1610462108,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "g2rl-apisero-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "U01EKS2C28M",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": true,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "Test Connectivity with Salesforce Slack",
      "creator": "U01EKS2C28M",
      "last_set": 1610462110
    },
    "num_members": 13
  },
  {
    "id": "C01JETMFMK7",
    "name": "northrockpartners-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1610462412,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "northrockpartners-apisero-shared",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UHR2CNW64",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 12
  },
  {
    "id": "C01JJFWDCV9",
    "name": "ati-restoration-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1610467328,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "ati-restoration-apisero-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "U01EN649BB9",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "ati-restoration",
      "creator": "U01EN649BB9",
      "last_set": 1610467329
    },
    "previous_names": [
      "ati-restoration"
    ],
    "num_members": 21
  },
  {
    "id": "C01JPA09AGP",
    "name": "medcan-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1611053607,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "medcan-apisero-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "UL4932YF8",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 14
  },
  {
    "id": "C01LLTSQ0AZ",
    "name": "chg-healthcare-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1612280918,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "chg-healthcare-apisero-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "UHR2CNW64",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 17
  },
  {
    "id": "C01LQEARCS0",
    "name": "apisero-valpak-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1612187203,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "apisero-valpak-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "UL4932YF8",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 15
  },
  {
    "id": "C01LQKW1WUU",
    "name": "apisero-snipesusa-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1612189629,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "apisero-snipesusa-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "UL4932YF8",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 8
  },
  {
    "id": "C01M9KS3H7E",
    "name": "apisero-bodiesdoneright-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1612504003,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "apisero-bodiesdoneright-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "UL4932YF8",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 10
  },
  {
    "id": "C01MPS5J747",
    "name": "apisero-g2rl-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1613397315,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "apisero-g2rl-shared",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "U01EKS2C28M",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "T596V2PB7",
    "is_member": true,
    "is_private": true,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "Private channel for communication between G2RL and Apisero team",
      "creator": "U01EKS2C28M",
      "last_set": 1613397316
    },
    "num_members": 14
  },
  {
    "id": "C01MUARV10B",
    "name": "intermedia-apisero-shared",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1613062338,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "intermedia-apisero-shared",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UHR2CNW64",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 10
  },
  {
    "id": "C01F12P2QSC",
    "name": "carltonone-apisero-mulesoft",
    "is_channel": true,
    "is_group": false,
    "is_im": false,
    "created": 1604932653,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "carltonone-apisero-mulesoft",
    "is_shared": true,
    "parent_conversation": null,
    "creator": "UCESWMG69",
    "is_ext_shared": true,
    "is_org_shared": false,
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "conversation_host_id": "TCE5JHR25",
    "is_member": true,
    "is_private": false,
    "is_mpim": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "previous_names": [],
    "num_members": 25
  },
  {
    "id": "G017PH4F10X",
    "name": "pluralsight-apisero-shared",
    "is_channel": false,
    "is_group": true,
    "is_im": false,
    "created": 1596300293,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "pluralsight-apisero-shared",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UFXNJ42DT",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": true,
    "is_mpim": false,
    "last_read": "1613620307.021700",
    "is_open": true,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "priority": 0.68894182526002
  },
  {
    "id": "G017XHG8S4W",
    "name": "independentpetpartners-apisero-shared",
    "is_channel": false,
    "is_group": true,
    "is_im": false,
    "created": 1596300292,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "independentpetpartners-apisero-shared",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UFXNJ42DT",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": true,
    "is_mpim": false,
    "last_read": "1613584986.019800",
    "is_open": true,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "priority": 0.40066602331081
  },
  {
    "id": "G0184FLUULT",
    "name": "abaco-apisero",
    "is_channel": false,
    "is_group": true,
    "is_im": false,
    "created": 1596300291,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "abaco-apisero",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UFU7VJSCU",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": true,
    "is_mpim": false,
    "last_read": "1613458301.038800",
    "is_open": true,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "priority": 0.14261357031875
  },
  {
    "id": "G0184FM01SP",
    "name": "ross-apisero-shared",
    "is_channel": false,
    "is_group": true,
    "is_im": false,
    "created": 1596300293,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "ross-apisero-shared",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "UFU0HJU67",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": true,
    "is_mpim": false,
    "last_read": "1612729075.000400",
    "is_open": true,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "priority": 0.032241058728803
  },
  {
    "id": "G01L7L7LGEB",
    "name": "mpdm-sero.bot--dipti.ukirade--irshad.ahmad-1",
    "is_channel": false,
    "is_group": true,
    "is_im": false,
    "created": 1612257675,
    "is_archived": false,
    "is_general": false,
    "unlinked": 0,
    "name_normalized": "mpdm-sero.bot--dipti.ukirade--irshad.ahmad-1",
    "is_shared": false,
    "parent_conversation": null,
    "creator": "U01H2KZPXQS",
    "is_ext_shared": false,
    "is_org_shared": false,
    "shared_team_ids": [
      "T596V2PB7"
    ],
    "pending_shared": [],
    "pending_connected_team_ids": [],
    "is_pending_ext_shared": false,
    "is_member": true,
    "is_private": true,
    "is_mpim": true,
    "last_read": "1612257736.001000",
    "is_open": false,
    "topic": {
      "value": "",
      "creator": "",
      "last_set": 0
    },
    "purpose": {
      "value": "Group messaging with: @sero.bot @dipti.ukirade @irshad.ahmad",
      "creator": "U01H2KZPXQS",
      "last_set": 1612257675
    },
    "priority": 0.040293469873291
  }
])